version: "3.7"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: teach
      MYSQL_USER: teacher
      MYSQL_PASSWORD: test
  image-database:
    image: mariadb
    restart: always
    ports:
      - 3306:3307
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: images
      MYSQL_USER: artist
      MYSQL_PASSWORD: test
  redis_db:
    image: redislabs/rejson
    restart: always
    ports:
      - 6379:6379
  libraries:
    image: node:12.4.0
    working_dir: /libraries
    command: sh ./watch.sh
    volumes:
      - ./libraries:/libraries
  proxy:
    image: traefik
    command: --docker
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  main-api:
    image: node:12.4.0
    working_dir: /app
    command: npm run watch
    tty: true
    labels:
      - traefik.enabled=true
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.teachelly.com
      - traefik.port=5000
    depends_on:
      - database
      - redis_db
      - libraries
    volumes:
      - ./apis/main--api:/app
      - ./libraries/common-library:/app/node_modules/common-library
      - ./libraries/server-lib:/app/node_modules/server-lib
    environment:
      NODE_ENV: development
      DATABASE_USER: teacher
      DATABASE_NAME: teach
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: test
      SERVER_PORT: 5000
      APPLICATION_KEYS: sjdflku84939ejdeiofe93
      SES_KEY: test
      SES_SECRET: test
      RECAPTCHA_SECRET: 6LfR7g8TAAAAAIx0qNIwowCKANmn2XA6HG2x-vUQ
      FORCE_DROP_DATABASE: "true"
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
  image-api:
    image: node:12.4.0
    working_dir: /app
    command: npm run watch
    tty: true
    environment:
      SERVER_PORT: 6000
      NODE_ENV: development
      USER_IMAGES_PATH: /images/generated 
      STATIC_IMAGES_PATH: /images/static
      DATABASE_NAME: images
      DATABASE_USER: artist
      DATABASE_HOST: image-database
      DATABASE_PASSWORD: test
      DATABASE_PORT: 3306
      FORCE_DROP_DATABASE: "true"
      REDIS_HOSSST: redis_db
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    labels:
      - traefik.enabled=true
      - traefik.backend=image-service
      - traefik.frontend.rule=Host:images.teachelly.com
      - traefik.port=6000
    volumes:
      - ./apis/image-api:/app
      - ./apis/image-api/images:/images
      - ./libraries/common-library:/app/node_modules/common-library
      - ./libraries/server-lib:/app/node_modules/server-lib
    depends_on:
      - redis_db
      - libraries
  frontend:
    image: node:12.4.0
    working_dir: /frontend
    command: npm run start
    tty: true
    labels:
      - traefik.frontend1.enabled=true
      - traefik.frontend1.backend=frontend
      - traefik.frontend1.frontend.rule=Host:teachelly.com
      - traefik.frontend1.port=3000
    volumes:
      - ./frontend:/frontend
      - ./libraries/common-library:/frontend/node_modules/common-library
    depends_on:
      - api
      - image-service
