version: "3.7"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: teach
      MYSQL_USER: teacher
      MYSQL_PASSWORD: test
  image-database:
    image: mariadb
    restart: always
    ports:
      - 3306:3307
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: images
      MYSQL_USER: artist
      MYSQL_PASSWORD: test
  redis_db:
    image: redislabs/rejson
    restart: always
    ports:
      - 6379:6379