version: "3.7"

services:
  database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: teach
      MYSQL_USER: teacher
      MYSQL_PASSWORD: test
    volumes:
      - ./database:/var/lib/mysql
  redis_db:
    image: redislabs/rejson
    restart: always
    ports:
      - 6379:6379
