export enum ErrorMessage {
	EMPTY = "error.empty",
	PASSWORDS_DONT_MATCH = "error.passwordsDontMatch",
	TOO_SHORT = "error.tooShort",
	TOO_LONG = "error.tooLong",
	WRONG_LENGTH = "error.wrongLength",
	BAD_CAPTCHA = "error.badCaptcha",
	DATE_TOO_BIG = "error.dateTooBig",
	DATE_TOO_SMALL = "error.dateTooSmall",
	INVALID_EMAIL = "error.invalidEmail",
	EMAIL_EXISTS = "error.emailExists",
	USER_NOT_FOUND = "error.userNotFound",
	USER_TOO_YOUNG = "error.userTooYoung",
	UNKNOWN = "error.unknown",
	COMPONENT = "error.component",
	UNAUTHORIZED = "error.unauthorized",
	INTERNAL_SERVER_ERROR = "error.internalServerError",
	NOT_SET = "error.notSet",
	PASSWORD_AND_EMAIL_SAME = "error.passwordAndEmailSame"
}