export * from "./IForgotInput";
export * from "./ILoginInput";
export * from "./IRegistrationInput";
export * from "./IResetPasswordInput";
export * from "./IAdListInput";
export * from "./ISimpleGetInput";
export * from "./IPersonalInput";
export * from "./IPasswordInput";
export * from "./IManySettingsInput";